# Generated by Django 6.0.6 on 2026-06-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0002_rename_orderitem_cartitem_cart_alter_cartitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='drug',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='drugs', to='pharmacies.tag'),
        ),
    ]
