# Generated by Django 6.0.6 on 2026-06-19 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='CartItem',
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(choices=[('self_delivery', 'Bron qilish (samovivoz)'), ('delivery', 'Yetkazib berish (dostavka)')], max_length=20)),
                ('status', models.CharField(choices=[('pending_receipt', 'Retsept kutilmoqda'), ('reviewing', 'Retsept tekshirilmoqda'), ('approved_assembling', 'Tasdiqlandi, joylanmoqda'), ('ready', 'Olib ketish uchun tayyor'), ('on_the_way', 'Yetkazib beruvchi yolda'), ('delivered', 'Yetkazildi'), ('rejected', 'Rad etildi')], default='pending_receipt', max_length=30)),
                ('prescription_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='pharmacies.pharmacy')),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacies.cart'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
