# Generated by Django 6.0.6 on 2026-06-29 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0003_tag_remove_pharmacy_phone_number_drug_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='prescription_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
    ]
