# Generated by Django 6.0.6 on 2026-06-29 05:10

import authorization.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', authorization.models.CustomUserManager()),
            ],
        ),
    ]
