# Generated by Django 6.0.6 on 2026-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('pharmacy', 'Pharmacy'), ('courier', 'Courier')], default='user'),
        ),
    ]
